version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mcp
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_BASE_URL=${LLM_API_BASE_URL}
      - LLM_DEFAULT_MODEL=${LLM_DEFAULT_MODEL}
      - VECTOR_DB_TYPE=qdrant
      - VECTOR_DB_URL=http://vector-db:6333
    volumes:
      - ./app:/app/app
    depends_on:
      - db
      - vector-db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

volumes:
  postgres-data:
  qdrant-data: